### PR TITLE
Coverage report for unit test

### PR DESCRIPTION
**Pull request by sudhirverma**
Relates to #9

### CODE REVIEW

**Comment by sudhirverma** [comment]
I want to add coverage report for CLI that is why I added this code

**Comment by dgolovin** [comment]
@jrichter1 I think @sudhirverma is aking for jenkins CI that would run the tests and record coverage report the same way we have it for vscode-adapters.

@jrichter1 BTW could we setup unit tests code coverage check for PRs? The same way we had for DevTools Installer?

**Comment by jrichter1** [comment]
@dgolovin and I am saying that coverage is already part of npm test

And I'd love to, but apparently to enable codecov one needs admin access to redhat-developer (or I'm missing something obvious)

**Comment by dgolovin** [comment]
Closing, because coverage is already there.

**Pull request closed without merging**
