### PR TITLE
Update rsp-client to use 0.11.0.Final protocol

### PR DESCRIPTION
**Pull request by robstryker**
Signed-off-by: Rob Stryker <rob@oxbeef.net>

### CODE REVIEW

**Comment by adietish** [comment]
compiles fine & runs tests successfully for me. 
Did not test it manually in vscode though.

**Comment by jrichter1** [comment]
Since nobody updated the tests, they are bound to fail with a change to the API. 
There are still multiple references to Protocol.ServerStateChange, which is being removed. And I bet even after that gets fixed, there will be other failures. So I have no idea how @adietish could get a successful test run out of this.

Anyhow, the tests don't get compiled along with the source, but rather when you try to run them. I should probably change that so you get an error like this straight away.

**Comment by adietish** [comment]
0.11.Final is a borked release, we need to use 0.12

**Comment by robstryker** [comment]
testPR

**Comment by dgolovin** [comment]
Should be rebased on top of master to fix issues with running test.

**Comment by adietish** [comment]
@dgolovin I rebased and had to install mocha globally to be able to run the tests.
Now the tests still fail:
```
/Users/adietish/Documents/jboss-workspaces/rsp-client/node_modules/ts-node/src/index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
test/client-test.ts(99,33): error TS2694: Namespace '"/Users/adietish/Documents/jboss-workspaces/rsp-client/src/protocol/protocol".Protocol' has no exported member 'ServerStateChange'.

    at createTSError (/Users/adietish/Documents/jboss-workspaces/rsp-client/node_modules/ts-node/src/index.ts:261:12)
    at getOutput (/Users/adietish/Documents/jboss-workspaces/rsp-client/node_modules/ts-node/src/index.ts:367:40)
    at Object.compile (/Users/adietish/Documents/jboss-workspaces/rsp-client/node_modules/ts-node/src/index.ts:558:11)
    at Module.m._compile (/Users/adietish/Documents/jboss-workspaces/rsp-client/node_modules/ts-node/src/index.ts:439:43)
    at module.exports (/Users/adietish/Documents/jboss-workspaces/rsp-client/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at /Users/adietish/Documents/jboss-workspaces/rsp-client/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/Users/adietish/Documents/jboss-workspaces/rsp-client/node_modules/ts-node/src/index.ts:442:12)
    at Object.<anonymous> (/Users/adietish/Documents/jboss-workspaces/rsp-client/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /usr/local/lib/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/usr/local/lib/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/usr/local/lib/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module.replacementCompile (/Users/adietish/Documents/jboss-workspaces/rsp-client/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/Users/adietish/Documents/jboss-workspaces/rsp-client/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/Users/adietish/Documents/jboss-workspaces/rsp-client/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at runMain (/Users/adietish/.node-spawn-wrap-56647-a20a6d968d0a/node:68:10)
    at Function.<anonymous> (/Users/adietish/.node-spawn-wrap-56647-a20a6d968d0a/node:171:5)
    at Object.<anonymous> (/Users/adietish/Documents/jboss-workspaces/rsp-client/node_modules/nyc/bin/wrap.js:23:4)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at /Users/adietish/.node-spawn-wrap-56647-a20a6d968d0a/node:178:8
    at Object.<anonymous> (/Users/adietish/.node-spawn-wrap-56647-a20a6d968d0a/node:181:3)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
------------------|----------|----------|----------|----------|-------------------|
File              |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
------------------|----------|----------|----------|----------|-------------------|
All files         |    82.35 |     96.3 |       75 |    82.35 |                   |
 src              |        0 |        0 |        0 |        0 |                   |
  main.ts         |        0 |        0 |        0 |        0 |                   |
 src/protocol     |      100 |      100 |      100 |      100 |                   |
  messages.ts     |      100 |      100 |      100 |      100 |                   |
 src/util         |    53.33 |       40 |     7.14 |    53.33 |                   |
  capabilities.ts |       50 |        0 |        0 |       50 |          18,27,37 |
  common.ts       |    53.85 |       50 |     9.09 |    53.85 |... 54,55,60,61,72 |
------------------|----------|----------|----------|----------|-------------------|
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rsp-client@0.0.5 test: `nyc mocha`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rsp-client@0.0.5 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by adietish** [comment]
@dgolovin I rebased and had to install mocha globally to be able to run the tests.
Now the tests still fail:
```
/Users/adietish/Documents/jboss-workspaces/rsp-client/node_modules/ts-node/src/index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
test/client-test.ts(99,33): error TS2694: Namespace '"/Users/adietish/Documents/jboss-workspaces/rsp-client/src/protocol/protocol".Protocol' has no exported member 'ServerStateChange'.

    at createTSError (/Users/adietish/Documents/jboss-workspaces/rsp-client/node_modules/ts-node/src/index.ts:261:12)
    at getOutput (/Users/adietish/Documents/jboss-workspaces/rsp-client/node_modules/ts-node/src/index.ts:367:40)
    at Object.compile (/Users/adietish/Documents/jboss-workspaces/rsp-client/node_modules/ts-node/src/index.ts:558:11)
    at Module.m._compile (/Users/adietish/Documents/jboss-workspaces/rsp-client/node_modules/ts-node/src/index.ts:439:43)
    at module.exports (/Users/adietish/Documents/jboss-workspaces/rsp-client/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at /Users/adietish/Documents/jboss-workspaces/rsp-client/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/Users/adietish/Documents/jboss-workspaces/rsp-client/node_modules/ts-node/src/index.ts:442:12)
    at Object.<anonymous> (/Users/adietish/Documents/jboss-workspaces/rsp-client/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /usr/local/lib/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/usr/local/lib/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/usr/local/lib/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module.replacementCompile (/Users/adietish/Documents/jboss-workspaces/rsp-client/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/Users/adietish/Documents/jboss-workspaces/rsp-client/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/Users/adietish/Documents/jboss-workspaces/rsp-client/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at runMain (/Users/adietish/.node-spawn-wrap-56647-a20a6d968d0a/node:68:10)
    at Function.<anonymous> (/Users/adietish/.node-spawn-wrap-56647-a20a6d968d0a/node:171:5)
    at Object.<anonymous> (/Users/adietish/Documents/jboss-workspaces/rsp-client/node_modules/nyc/bin/wrap.js:23:4)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at /Users/adietish/.node-spawn-wrap-56647-a20a6d968d0a/node:178:8
    at Object.<anonymous> (/Users/adietish/.node-spawn-wrap-56647-a20a6d968d0a/node:181:3)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
------------------|----------|----------|----------|----------|-------------------|
File              |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
------------------|----------|----------|----------|----------|-------------------|
All files         |    82.35 |     96.3 |       75 |    82.35 |                   |
 src              |        0 |        0 |        0 |        0 |                   |
  main.ts         |        0 |        0 |        0 |        0 |                   |
 src/protocol     |      100 |      100 |      100 |      100 |                   |
  messages.ts     |      100 |      100 |      100 |      100 |                   |
 src/util         |    53.33 |       40 |     7.14 |    53.33 |                   |
  capabilities.ts |       50 |        0 |        0 |       50 |          18,27,37 |
  common.ts       |    53.85 |       50 |     9.09 |    53.85 |... 54,55,60,61,72 |
------------------|----------|----------|----------|----------|-------------------|
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rsp-client@0.0.5 test: `nyc mocha`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rsp-client@0.0.5 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Pull request merged**
